import type { Article, Produit } from "./types";

/**
 * Jeu de données d'essai (spec §2.4) : 15 produits fictifs, prix à `null`
 * partout. Les titres repris sont des titres publics utilisés à titre
 * d'exemple pour la maquette — aucun prix ni stock réel n'est représenté.
 */
export const PRODUITS: Produit[] = [
  {
    id: "ea-sports-fc-25",
    nom: "EA Sports FC 25",
    categorie: "Jeux",
    images: ["fc25-1", "fc25-2"],
    imageBanniere: "ea-sports-fc-25-banniere",
    description: "[Description à fournir]",
    genres: ["Sport"],
    variantes: [
      { plateforme: "PS5", prix: null, disponibilite: "En stock" },
      { plateforme: "PS4", prix: null, disponibilite: "En stock" },
      { plateforme: "Xbox Series", prix: null, disponibilite: "En stock" },
      { plateforme: "Nintendo Switch", prix: null, disponibilite: "Sur commande" },
    ],
    miseEnAvant: true,
    dateAjout: "2026-08-05",
  },
  {
    id: "god-of-war-ragnarok",
    nom: "God of War Ragnarök",
    categorie: "Jeux",
    images: ["gow-1"],
    imageBanniere: "god-of-war-ragnarok-banniere",
    description: "[Description à fournir]",
    genres: ["Action", "Aventure"],
    variantes: [
      { plateforme: "PS5", prix: null, disponibilite: "En stock" },
      { plateforme: "PS4", prix: null, disponibilite: "En stock" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-07-20",
  },
  {
    id: "forza-horizon-5",
    nom: "Forza Horizon 5",
    categorie: "Jeux",
    images: ["forza-1"],
    imageBanniere: "forza-horizon-5-banniere",
    description: "[Description à fournir]",
    genres: ["Course"],
    variantes: [
      { plateforme: "Xbox Series", prix: null, disponibilite: "En stock" },
      { plateforme: "Xbox One", prix: null, disponibilite: "En stock" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-06-14",
  },
  {
    id: "zelda-totk",
    nom: "The Legend of Zelda: Tears of the Kingdom",
    categorie: "Jeux",
    images: ["zelda-1"],
    imageBanniere: "zelda-totk-banniere",
    description: "[Description à fournir]",
    genres: ["Aventure", "Rôle"],
    variantes: [
      { plateforme: "Nintendo Switch", prix: null, disponibilite: "Sur commande" },
    ],
    miseEnAvant: true,
    dateAjout: "2026-08-08",
  },
  {
    id: "mortal-kombat-1",
    nom: "Mortal Kombat 1",
    categorie: "Jeux",
    images: ["mk1-1"],
    imageBanniere: "mortal-kombat-1-banniere",
    description: "[Description à fournir]",
    genres: ["Combat"],
    variantes: [
      { plateforme: "PS5", prix: null, disponibilite: "En stock" },
      { plateforme: "Xbox Series", prix: null, disponibilite: "En stock" },
      { plateforme: "Nintendo Switch", prix: null, disponibilite: "Épuisé" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-05-02",
  },
  {
    id: "mario-kart-8-deluxe",
    nom: "Mario Kart 8 Deluxe",
    categorie: "Jeux",
    images: ["mk8-1"],
    imageBanniere: "mario-kart-8-deluxe-banniere",
    description: "[Description à fournir]",
    genres: ["Course", "Famille"],
    variantes: [
      { plateforme: "Nintendo Switch", prix: null, disponibilite: "En stock" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-04-11",
  },
  {
    id: "sonic-the-hedgehog-2",
    nom: "Sonic the Hedgehog 2",
    categorie: "Jeux",
    images: ["sonic-1"],
    imageBanniere: "sonic-the-hedgehog-2-banniere",
    description: "[Description à fournir]",
    genres: ["Action", "Famille"],
    variantes: [
      { plateforme: "Rétro", prix: null, disponibilite: "En stock" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-03-01",
  },
  {
    id: "console-playstation-5",
    nom: "Console PlayStation 5",
    categorie: "Consoles",
    images: ["ps5-console-1", "ps5-console-2"],
    imageBanniere: "console-playstation-5-banniere",
    description: "[Description à fournir]",
    variantes: [
      { plateforme: "PS5", prix: null, disponibilite: "En stock" },
    ],
    miseEnAvant: true,
    dateAjout: "2026-08-01",
  },
  {
    id: "console-xbox-series-x",
    nom: "Console Xbox Series X",
    categorie: "Consoles",
    images: ["xbox-console-1"],
    imageBanniere: "console-xbox-series-x-banniere",
    description: "[Description à fournir]",
    variantes: [
      { plateforme: "Xbox Series", prix: null, disponibilite: "Sur commande" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-07-15",
  },
  {
    id: "console-nintendo-switch-oled",
    nom: "Nintendo Switch OLED",
    categorie: "Consoles",
    images: ["switch-console-1"],
    imageBanniere: "console-nintendo-switch-oled-banniere",
    description: "[Description à fournir]",
    variantes: [
      { plateforme: "Nintendo Switch", prix: null, disponibilite: "En stock" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-06-25",
  },
  {
    id: "manette-dualsense",
    nom: "Manette DualSense",
    categorie: "Manettes",
    images: ["dualsense-1"],
    imageBanniere: "manette-dualsense-banniere",
    description: "[Description à fournir]",
    variantes: [
      { plateforme: "PS5", prix: null, disponibilite: "En stock" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-07-02",
  },
  {
    id: "manette-joy-con-paire",
    nom: "Paire de manettes Joy-Con",
    categorie: "Manettes",
    images: ["joycon-1"],
    imageBanniere: "manette-joy-con-paire-banniere",
    description: "[Description à fournir]",
    variantes: [
      { plateforme: "Nintendo Switch", prix: null, disponibilite: "En stock" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-05-18",
  },
  {
    id: "casque-gaming-universel",
    nom: "Casque gaming universel",
    categorie: "Accessoires",
    images: ["casque-1"],
    imageBanniere: "casque-gaming-universel-banniere",
    description: "[Description à fournir]",
    variantes: [{ plateforme: "Multi", prix: null, disponibilite: "En stock" }],
    miseEnAvant: false,
    dateAjout: "2026-04-28",
  },
  {
    id: "cable-hdmi-2-1",
    nom: "Câble HDMI 2.1 universel",
    categorie: "Accessoires",
    images: ["cable-1"],
    imageBanniere: "cable-hdmi-2-1-banniere",
    description: "[Description à fournir]",
    variantes: [{ plateforme: "Multi", prix: null, disponibilite: "Épuisé" }],
    miseEnAvant: false,
    dateAjout: "2026-02-19",
  },
  {
    id: "carte-cadeau-playstation-store",
    nom: "Carte cadeau PlayStation Store",
    categorie: "Cartes cadeaux",
    images: ["carte-psn-1"],
    imageBanniere: "carte-cadeau-playstation-store-banniere",
    description: "[Description à fournir]",
    variantes: [
      { plateforme: "PS5", prix: null, disponibilite: "En stock" },
    ],
    miseEnAvant: false,
    dateAjout: "2026-08-09",
  },
];

/** Trois articles de substitution pour /nouvelles (spec §5.7). */
export const ARTICLES: Article[] = [
  {
    id: "article-1",
    titre: "[Titre à fournir]",
    image: "article-1",
    resume: "[Contenu à fournir]",
    contenu: "[Contenu à fournir]",
    date: "2026-08-05",
    type: "Offre",
  },
  {
    id: "article-2",
    titre: "[Titre à fournir]",
    image: "article-2",
    resume: "[Contenu à fournir]",
    contenu: "[Contenu à fournir]",
    date: "2026-07-22",
    type: "Événement",
  },
  {
    id: "article-3",
    titre: "[Titre à fournir]",
    image: "article-3",
    resume: "[Contenu à fournir]",
    contenu: "[Contenu à fournir]",
    date: "2026-06-30",
    type: "Annonce",
  },
];

export function produitParId(id: string): Produit | undefined {
  return PRODUITS.find((p) => p.id === id);
}
